#lang pollen

◊`(div ([class "lg:flex lg:justify-between lg:gap-4"])
  (header ([class "lg:sticky lg:top-0 lg:flex lg:max-h-screen lg:w-1/2 lg:flex-col lg:justify-between lg:py-24"])
	(div
		(h1 ([class "text-3xl font-base tracking-wide text-zinc-200 sm:text-4xl"])
		    "Säms Gschenk")
		(h2 ([class "mt-2 text-lg text-zinc-200 sm:text-lg"])
		◊; (p ([class "mt-4 max-w-xs leading-normal"])
		    "Wichteln 2023, Lago Edition")
		◊; (p ([class "mt-4 max-w-xs leading-normal"])
		◊; 	"")
	))

  (main ([class "pt-24 lg:w-1/2 lg:py-24"])

	(section ([id "what"] [class "mb-8 group/section scroll-mt-8 lg:scroll-mt-0"] [aria-label "What"])
			 (div ([class "lg:w-10/12"])
			 	  (p 
						 "Lieber Säm,")
			 	  (p ([class "mt-4"])
						 "ich habe lange überlegt, ob ich es wagen soll, dir doch so etwas Ungewöhnliches zu schenken, und habe mich entschlossen, es jetzt einfach mal zu versuchen. Ich hoffe, es gefällt dir – noch gespannter bin ich aber darauf, was du dazu sagst.")
			 	  (p ([class "mt-4"])
					   "Soo. Was haben wir denn anzubieten?")
				))
	(section ([id "poem-1"] [class "mb-8 group/section scroll-mt-8 lg:scroll-mt-0"] [aria-label "poem-1"])
			 (div ([class "sticky top-0 z-20 -mx-6 mt-8 w-screen px-6 py-5 backdrop-blur md:-mx-12 md:px-12 lg:px-1 lg:py-1 lg:mt-0 lg:mb-4 lg:mx-0 lg:w-5/6"])
			 	  ,(section-title "◊"))
			 (div ([class "lg:w-10/12 italic"])
			 	  (p "Do not go gentle into that good night,")
					(p "Old age should burn and rave at close of day;")
					(p "Rage, rage against the dying of the light.")

					(p ([class "mt-4"])
						 "Though wise men at their end know dark is right,")
					(p "Because their words had forked no lightning they")
					(p "Do not go gentle into that good night.")

					(p ([class "mt-4"])
						 "Good men, come on it the last wave by, crying how bright")
					(p "Their frail deeds might have danced in a green bay,")
					(p "Rage, rage against the dying of the light.")

					(p ([class "mt-4"])
						 "Wild men who caught and sang the sun in flight,")
					(p "And learn, too late, they grieved it on its way,")
					(p "Do not go gentle into that good night.")

					(p ([class "mt-4"])
						 "Grave men, near death, who see with blinding sight")
					(p "Blind eyes could blaze like meteors and be gay,")
					(p "Rage, rage against the dying of the light.")

					(p ([class "mt-4"])
						 "And you, my father, there on that sad height,")
					(p "Curse, bless, me now with your fierce tears, I pray.")
					(p "Do not go gentle into that good night.")
					(p "Rage, rage against the dying of the light.")
					(p "")
			 	  (p ([class "mt-4"])
					   "")
			 	  (p ([class "mt-4"])
					   "")
			 	  (p ([class "mt-4"])
					   "")
				))
	(section ([id "movies-1"] [class "mb-8 group/section scroll-mt-8 lg:scroll-mt-0"] [aria-label "movies-1"])
			 (div ([class "sticky top-0 z-20 -mx-6 mt-8 w-screen px-6 py-5 backdrop-blur md:-mx-12 md:px-12 lg:px-1 lg:py-1 lg:mt-0 lg:mb-4 lg:mx-0 lg:w-5/6"])
			 	  ,(section-title "\\"))
			 (div ([class "lg:w-10/12"])
					(p "V for Vendetta")
			 	  (p ([class "mt-4"])
					   "Der Gott des Gemetzels")
			 	  (p ([class "mt-4"])
					   "")
			 	  (p ([class "mt-4"])
					   "")
				))
	(section ([id "talks-1"] [class "mb-8 group/section scroll-mt-8 lg:scroll-mt-0"] [aria-label "talks-1"])
			 (div ([class "sticky top-0 z-20 -mx-6 mt-8 w-screen px-6 py-5 backdrop-blur md:-mx-12 md:px-12 lg:px-1 lg:py-1 lg:mt-0 lg:mb-4 lg:mx-0 lg:w-5/6"])
			 	  ,(section-title "/"))
			 (div ([class "lg:w-10/12"])
					(p ,(link "Email vs Capitalism" "https://www.youtube.com/watch?v=mrGfahzt-4Q"))
			 	  (p ([class "mt-4"])
					   ,(link "Simple made easy" "https://www.infoq.com/presentations/Simple-Made-Easy/"))
			 	  (p ([class "mt-4"])
					   "")
				))
	(section ([id "articles-1"] [class "mb-8 group/section scroll-mt-8 lg:scroll-mt-0"] [aria-label "articles-1"])
			 (div ([class "sticky top-0 z-20 -mx-6 mt-8 w-screen px-6 py-5 backdrop-blur md:-mx-12 md:px-12 lg:px-1 lg:py-1 lg:mt-0 lg:mb-4 lg:mx-0 lg:w-5/6"])
			 	  ,(section-title "≈"))
			 (div ([class "lg:w-10/12"])
					(p ,(link "Be an Enigneer, not a frameworker" "https://johndanielraines.medium.com/be-an-engineer-not-a-frameworker-c58fe28d0c88"))
			 	  (p ([class "mt-4"])
					   ,(link "The four kinds of documentation" "https://www.writethedocs.org/videos/eu/2017/the-four-kinds-of-documentation-and-why-you-need-to-understand-what-they-are-daniele-procida/"))
			 	  (p ([class "mt-4"])
					   "")
				))

	(footer ([class "max-w-md pb-16 text-sm text-zinc-500 sm:pb-0"])
		(p ([class "mb-1"])
		   "Written with " ,(footer-link "the magnificent wichtel editor" "https://code.visualstudio.com/") ". Built with  " ,(footer-link "Racket" "https://racket-lang.com") ", " ,(footer-link "Pollen" "https://pollenpub.com") " and " ,(footer-link "Tailwind CSS" "https://tailwindcss.com") "."))
  )
)
